# Auto-increments the per-build firmware version counter and exposes the
# final firmware version to the firmware sources via a generated header.
#
# PlatformIO calls this script (platformio.ini -> extra_script) every time the
# environment is processed, including non-build commands such as `pio run
# --target clean` or `pio device monitor`. The counter therefore MUST be
# bumped only when an actual firmware build artifacts get produced, which we
# gate here on the build action that produces the final firmware binary.
#
# Version scheme: <MAJOR.MINOR>.<BUILD> where <MAJOR.MINOR> is a
# committed base version (firmware/version.txt) and <BUILD> is a counter that
# increases once per successful build (firmware/.build_count).
#
# The counter is bumped and the generated header written only right before the
# link (ensure_version_header). But compilation happens before that, so the
# header would otherwise describe the *previous* build (and be missing
# entirely / fall back to 0.0.0 on a fresh checkout). We therefore also write a
# provisional header at import time, i.e. before any source is compiled, using
# the version the upcoming link will produce. The pre-link step then rewrites
# the same value, so the persistent counter still advances only when a firmware
# is actually produced.
import os

Import("env")

BASE_VERSION_FILE = "version.txt"
BUILD_COUNT_FILE = ".build_count"
GENERATED_HEADER = "src/esp32/fw_version.h"

FW_VERSION_HEADER_TEMPLATE = """\
// Auto-generated by firmware/extra_script.py during the PlatformIO build.
// NOTE: never edit and never commit this file.
#ifndef FW_VERSION_H
#define FW_VERSION_H

#define FW_VERSION "{}"

#endif // FW_VERSION_H
"""


def _project_dir(env):
    return env.subst("$PROJECT_DIR")


def _read_version():
    base = "0.0.0"
    with open(os.path.join(_project_dir(env), BASE_VERSION_FILE), "r") as fh:
        value = fh.read().strip()
        if value:
            base = value
    return base


def _read_build_count():
    path = os.path.join(_project_dir(env), BUILD_COUNT_FILE)
    if not os.path.isfile(path):
        return 0
    with open(path, "r") as fh:
        try:
            return int(fh.read().strip() or "0")
        except ValueError:
            return 0


def _write_build_count(count):
    with open(os.path.join(_project_dir(env), BUILD_COUNT_FILE), "w") as fh:
        fh.write("{}\n".format(count))


def _generate_header(firmware_version):
    header = FW_VERSION_HEADER_TEMPLATE.format(firmware_version)
    with open(os.path.join(_project_dir(env), GENERATED_HEADER), "w") as fh:
        fh.write(header)


def _next_version():
    return "{}.{}".format(_read_version(), _read_build_count() + 1)


def _ensure_provisional_header(env):
    if env.subst("$PIOENV") != "esp32":
        return
    _generate_header(_next_version())


def ensure_version_header(target, source, env):
    if env.subst("$PIOENV") != "esp32":
        return

    build_count = _read_build_count() + 1
    _write_build_count(build_count)

    firmware_version = "{}.{}".format(_read_version(), build_count)
    _generate_header(firmware_version)

    print("FW_VERSION: {}".format(firmware_version))


_ensure_provisional_header(env)
env.AddPreAction("$BUILD_DIR/$PROGNAME$PROGSUFFIX", ensure_version_header)